#!/bin/sh

screenshot=$(maim -sBou | base64)

message=`smenu "Caption:" "$1" -noinput`

echo "$screenshot" | base64 --decode | magick - -bordercolor black -border 5 -bordercolor white -border 1 -bordercolor black -border "%[fx:w/4]"x"%[fx:h/4]" -font Times-Roman -fill white -pointsize "%[fx:(h/12)]" -gravity center -annotate +0+"%[fx:(5*h/12)]" "$message" png: | xclip -selection clipboard -t image/png 
