#!/bin/sh

declare dimension
case "$1" in
    "w")
        dimension=1
        ;;
    "h")
        dimension=2
        ;;
    "x")
        dimension=3
        ;;
    "y")
        dimension=4
        ;;
    *)
        echo "Invalid dimension"
        exit 1
        ;;
esac

screen=0
if ! [ -z "$2" ]; then
   screen="$2"
fi
let screen++
let screen++

xrandr --current --listmonitors --nograb |\
sed -n "${screen}p" |\
awk -F " " '{print $3}' |\
tr + x |\
awk -F "x" -v dimension="$dimension" '{print $dimension}' |\
awk -F "/" '{print $1}'
